#!/bin/sh

main() {
	wordToDefine=$1
	which dict > /dev/null || install 
	
	dict -d gcide $1
}

install() {
	echo "'dict' not found. Installing."
	sudo apt-get install dict dictd dict-gcide && echo "DONE."
}

main $1
